name: sync

on:
  push:
    branches:
      - master
      - main
  # schedule:
  #   - cron: "0 5 */3 * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-aliyun:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        export version=v1.10.0 && export  arch=amd64 && sudo wget https://github.com/lework/skopeo-binary/releases/download/${version}/skopeo-linux-${arch} -O /usr/bin/skopeo && sudo chmod +x /usr/bin/skopeo
        skopeo --version
    - name: sync image
      env:
        HUB_USERNAME: ${{ secrets.HUB_USERNAME }}
        HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}
      run: |
        bash sync.sh
